### PR TITLE
chore(deps): just bump EVERYTHING

### PR DESCRIPTION
**Pull request by louh**
maybe this actually kinda works

### CODE REVIEW

**Comment by chriszs** [comment]
Did:
```sh
yarn && yarn build
```

Got:
```sh
$ ./node_modules/gatsby-cli/lib/index.js build
warn Plugin gatsby-plugin-netlify-cache is not compatible with your gatsby version 4.4.0 - It requires gatsby@^2.0.0
warn Plugin gatsby-plugin-netlify-cache is not compatible with your gatsby version 4.4.0 - It requires gatsby@^2.0.0
success open and validate gatsby-configs, load plugins - 3.888s
warn gatsby-plugin-netlify-cache got deprecated. This version of the plugin will do nothing. Please migrate to https://github.com/netlify/netlify-plugin-gatsby
success onPreInit - 0.025s
# [...snip]
failed Building production JavaScript and CSS bundles - 22.840s

 ERROR #98123  WEBPACK

Generating JavaScript bundles failed

styles.5fe60b9918798dc09a87.css from Css Minimizer
BrowserslistError: Unknown browser kaios
    at checkName (/Users/chriszs/Desktop/work/BadIdeaFactory/biffud.com/node_modules/caniuse-api/node_modules/browserslist/index.js:124:20)
    at Function.select (/Users/chriszs/Desktop/work/BadIdeaFactory/biffud.com/node_modules/caniuse-api/node_modules/browserslist/index.js:750:18)
    at /Users/chriszs/Desktop/work/BadIdeaFactory/biffud.com/node_modules/caniuse-api/node_modules/browserslist/index.js:155:33
    at Array.reduce (<anonymous>)
    at resolve (/Users/chriszs/Desktop/work/BadIdeaFactory/biffud.com/node_modules/caniuse-api/node_modules/browserslist/index.js:136:18)
    at browserslist (/Users/chriszs/Desktop/work/BadIdeaFactory/biffud.com/node_modules/caniuse-api/node_modules/browserslist/index.js:252:16)
    at isSupported (/Users/chriszs/Desktop/work/BadIdeaFactory/biffud.com/node_modules/caniuse-api/dist/index.js:62:37)
    at Object.prepare (/Users/chriszs/Desktop/work/BadIdeaFactory/biffud.com/node_modules/postcss-reduce-initial/dist/index.js:33:58)
    at /Users/chriszs/Desktop/work/BadIdeaFactory/biffud.com/node_modules/postcss/lib/lazy-result.js:149:39
    at Array.map (<anonymous>)

File: styles.5fe60b9918798dc09a87.css


 ERROR #98123  WEBPACK

Generating JavaScript bundles failed

styles.56e8849fe8f0f0f6b8be.css from Css Minimizer
BrowserslistError: Unknown browser kaios
    at checkName (/Users/chriszs/Desktop/work/BadIdeaFactory/biffud.com/node_modules/caniuse-api/node_modules/browserslist/index.js:124:20)
    at Function.select (/Users/chriszs/Desktop/work/BadIdeaFactory/biffud.com/node_modules/caniuse-api/node_modules/browserslist/index.js:750:18)
    at /Users/chriszs/Desktop/work/BadIdeaFactory/biffud.com/node_modules/caniuse-api/node_modules/browserslist/index.js:155:33
    at Array.reduce (<anonymous>)
    at resolve (/Users/chriszs/Desktop/work/BadIdeaFactory/biffud.com/node_modules/caniuse-api/node_modules/browserslist/index.js:136:18)
    at browserslist (/Users/chriszs/Desktop/work/BadIdeaFactory/biffud.com/node_modules/caniuse-api/node_modules/browserslist/index.js:252:16)
    at isSupported (/Users/chriszs/Desktop/work/BadIdeaFactory/biffud.com/node_modules/caniuse-api/dist/index.js:62:37)
    at Object.prepare (/Users/chriszs/Desktop/work/BadIdeaFactory/biffud.com/node_modules/postcss-reduce-initial/dist/index.js:33:58)
    at /Users/chriszs/Desktop/work/BadIdeaFactory/biffud.com/node_modules/postcss/lib/lazy-result.js:149:39
    at Array.map (<anonymous>)

File: styles.56e8849fe8f0f0f6b8be.css


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by chriszs** [comment]
May be related to:
```
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
```

**Comment by chriszs** [comment]
`yarn upgrade` seems to have cleared it for me.

**Comment by slifty** [comment]
What's the verdict on this -- chris are you saying it's good to merge or is there something that should be changed first?

**Comment by chriszs** [comment]
Doesn't build. `yarn upgrade` seems to fix. Updates lock file.

**Comment by slifty** [comment]
Ran `yarn upgrade` and it seems to build; it does have:


```

 ERROR

Unexpected keys "componentDataDependencies", "pageData" found in preloadedState argument passed to createStore. Expected
to find one of the known reducer keys instead: "nodes", "logs", "pages", "redirects", "schema", "definitions",
"staticQueryComponents", "status", "webpack", "webpackCompilationHash", "config", "lastAction", "jobsV2", "pageDataStats",
 "components", "babelrc", "jobs", "nodesByType", "program", "resolvedNodesCache", "nodesTouched", "flattenedPlugins",
"pendingPageDataWrites", "schemaCustomization", "inferenceMetadata", "staticQueriesByTemplate", "queries", "visitedPages",
 "html", "functions", "nodeManifests", "pageTree". Unexpected keys will be ignored.
 ```
 
That said the build does indeed seem to work; I think I'm gonna push the upgrade, merge, and see if we can't close out the open PRs

**Comment by chriszs** [comment]
@slifty Interesting. I don't see that error.

**Pull request merged**
